run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - gci
    - gocritic
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace