
services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    ports:
      - "26257:26257"
      - "9090:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    command: start-single-node --insecure

volumes:
  cockroach-data:
    name: links-r-us-cockroach-data